#%RAML 1.0 NamedExample

value:
    - ID: 2
      code: ER38sd
      price: 400
      departureDate: 2025/07/31
      origin: CLE
      destination: SFO
      emptySeats: 0
      plane:
        planeType: Boeing 737
        totalSeats: 150
    - ID: 3
      code: ER45if
      price: 540.99
      departureDate: 2025/01/30
      origin: SFO
      destination: ORD
      emptySeats: 54
      plane:
        planeType: Boeing 777
        totalSeats: 300